version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: stationery_app
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
      DB_HOST: db
      DB_NAME: stationery_store
      DB_USER: app
      DB_PASS: app
      BASE_URL: ""
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: stationery_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: stationery_store
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro

  pma:
    image: phpmyadmin:5
    container_name: stationery_pma
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpass
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data: